name = "rndgen-fortran-examples"
version = "2.0.0"
license = "LGPL-3.0-or-later"
author = "Wesley Cota"
maintainer = "wlcota@gmail.com"
copyright = "Copyright 2026, Wesley Cota"

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[dev-dependencies]
rndgen-fortran = {git="https://github.com/wcota/rndgen-fortran", tag="a012b6833dd45478d3b7d6c3e39bff9a9a153377"}
