module julienne_lite_mod
    ! ==============================================================================
    ! Module : julienne_lite_mod
    ! Author : Generated by Google Gemini
    ! Inspired by the julienne library (https://github.com/berkeleylab/julienne)
    ! Date   : August 2026
    ! Purpose: Simplified and compiler-friendly fallback for the Julienne library
    !          to prevent coarray-related compilation issues in Fortran projects.
    ! ==============================================================================
    implicit none
    private

    ! Constantes de precisão (ajuste caso seu código já as importe globalmente)
    integer, parameter :: i4 = selected_int_kind(9)
    integer, parameter :: i8 = selected_int_kind(18)
    integer, parameter :: sp = selected_real_kind(6, 37)
    integer, parameter :: dp = selected_real_kind(15, 307)

    ! Tipos Públicos Exportados
    public :: test_diagnosis_t
    public :: approx_state_t

    ! Operadores Públicos Exportados
    public :: operator(.equalsExpected.)
    public :: operator(.also.)
    public :: operator(.all.)
    public :: operator(.isAtLeast.)
    public :: operator(.lessThan.)
    public :: operator(.isAtMost.)
    public :: operator(.approximates.)
    public :: operator(.within.)
    public :: assignment(=)

    ! ---------------------------------------------------------
    ! DEFINIÇÃO DOS TIPOS
    ! ---------------------------------------------------------
    type :: test_diagnosis_t
        logical :: passed = .false.
        character(len=256) :: msg = ""
    contains
        procedure :: test_passed => diag_test_passed
        procedure :: diagnostics_string => diag_diagnostics_string
    end type

    type :: approx_state_t
        real(dp) :: val, target
    end type

    ! ---------------------------------------------------------
    ! INTERFACES DOS OPERADORES
    ! ---------------------------------------------------------
    interface assignment(=)
        module procedure assign_log_to_diag
    end interface

    interface operator(.all.)
        module procedure all_logical_arr
    end interface

    interface operator(.equalsExpected.)
        module procedure eq_exp_i4
        module procedure eq_exp_logical
    end interface

    interface operator(.also.)
        module procedure also_diag
        module procedure also_log
    end interface

    interface operator(.isAtLeast.)
        module procedure is_at_least_dp
        module procedure is_at_least_sp
        module procedure is_at_least_i4
        module procedure is_at_least_i8
    end interface

    interface operator(.lessThan.)
        module procedure less_than_dp
        module procedure less_than_sp
    end interface

    interface operator(.isAtMost.)
        module procedure is_at_most_i4
        module procedure is_at_most_i8
    end interface

    interface operator(.approximates.)
        module procedure approx_dp
    end interface

    interface operator(.within.)
        module procedure within_dp
    end interface

contains

    ! ---------------------------------------------------------
    ! MÉTODOS DO TIPO test_diagnosis_t
    ! ---------------------------------------------------------
    function diag_test_passed(this) result(res)
        class(test_diagnosis_t), intent(in) :: this
        logical :: res
        res = this%passed
    end function

    function diag_diagnostics_string(this) result(res)
        class(test_diagnosis_t), intent(in) :: this
        character(len=256) :: res
        res = this%msg
    end function

    ! Permite fazer: check = (r1 .isAtLeast. 0.0)
    subroutine assign_log_to_diag(diag, val)
        class(test_diagnosis_t), intent(out) :: diag
        logical, intent(in) :: val
        diag%passed = val
        if (.not. val) diag%msg = "Falha em condicao escalar logica."
    end subroutine

    ! ---------------------------------------------------------
    ! OPERADORES DE REDUÇÃO E CONCATENAÇÃO
    ! ---------------------------------------------------------
    function all_logical_arr(arr) result(res)
        logical, intent(in) :: arr(:)
        type(test_diagnosis_t) :: res
        res%passed = all(arr)
        if (.not. res%passed) res%msg = "Um ou mais elementos do array falharam na condicao."
    end function

    function also_diag(a, b) result(res)
        type(test_diagnosis_t), intent(in) :: a, b
        type(test_diagnosis_t) :: res
        res%passed = a%passed .and. b%passed
        if (res%passed) then
            res%msg = ""
        else
            res%msg = trim(a%msg) // " | " // trim(b%msg)
        end if
    end function

    elemental function also_log(a, b) result(res)
        logical, intent(in) :: a, b
        logical :: res
        res = a .and. b
    end function

    function eq_exp_i4(a, b) result(res)
        integer(i4), intent(in) :: a, b
        type(test_diagnosis_t) :: res
        res%passed = (a == b)
        if (.not. res%passed) res%msg = "Falha: Valores inteiros nao sao iguais."
    end function

    function eq_exp_logical(a, b) result(res)
        logical, intent(in) :: a, b
        type(test_diagnosis_t) :: res
        res%passed = (a .eqv. b)
        if (.not. res%passed) res%msg = "Falha: Estados logicos nao sao equivalentes."
    end function

    ! ---------------------------------------------------------
    ! OPERADORES ELEMENTAIS (resolvem os erros de vetorização)
    ! ---------------------------------------------------------
    elemental function is_at_least_dp(a, b) result(res)
        real(dp), intent(in) :: a, b; logical :: res; res = (a >= b)
    end function

    elemental function is_at_least_sp(a, b) result(res)
        real(sp), intent(in) :: a, b; logical :: res; res = (a >= b)
    end function

    elemental function is_at_least_i4(a, b) result(res)
        integer(i4), intent(in) :: a, b; logical :: res; res = (a >= b)
    end function

    elemental function is_at_least_i8(a, b) result(res)
        integer(i8), intent(in) :: a, b; logical :: res; res = (a >= b)
    end function

    elemental function less_than_dp(a, b) result(res)
        real(dp), intent(in) :: a, b; logical :: res; res = (a < b)
    end function

    elemental function less_than_sp(a, b) result(res)
        real(sp), intent(in) :: a, b; logical :: res; res = (a < b)
    end function

    elemental function is_at_most_i4(a, b) result(res)
        integer(i4), intent(in) :: a, b; logical :: res; res = (a <= b)
    end function

    elemental function is_at_most_i8(a, b) result(res)
        integer(i8), intent(in) :: a, b; logical :: res; res = (a <= b)
    end function

    ! ---------------------------------------------------------
    ! OPERADORES DE APROXIMAÇÃO
    ! ---------------------------------------------------------
    function approx_dp(a, b) result(res)
        real(dp), intent(in) :: a, b
        type(approx_state_t) :: res
        res%val = a
        res%target = b
    end function

    function within_dp(state, tol) result(res)
        type(approx_state_t), intent(in) :: state
        real(dp), intent(in) :: tol
        type(test_diagnosis_t) :: res
        res%passed = (abs(state%val - state%target) <= tol)
        if (.not. res%passed) res%msg = "Falha: Valor fora da tolerancia permitida."
    end function

end module julienne_lite_mod